language: node_js
node_js:
  - '0.10'
  - '0.11'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-nomo' ]; then cd .. && eval "mv $currentfolder generator-nomo" && cd generator-nomo; fi

